#!/bin/bash

# exporting variables
# { VERSION
# }

. tester

function updateversion {
  argn 1

  echo $1 > $WKDIR/version
}

function b_init_shortc {
  argn 0

  if ! b_init_tester; then return 1; fi
  mkdir $WKDIR/versions

  updateversion 0

  return 0;
}

function v_load_shortc {
  argn 0

  if ! v_load_tester; then return $?; fi

  if ! [ -d $WKDIR/versions ]; then return 11; fi
  if ! [ -f $WKDIR/version ]; then return 12; fi

  VERSION=`cat $WKDIR/version`

  local num=`ls $WKDIR/versions | wc -l`
  if [ $num != $VERSION ]; then return 13; fi

  return 0
  # 0 = success, all works fine!
  # 1 = WKDIR/versions damaged
  # 2 = WKDIR/version damaged
  # 3 = versions are not properly perserved
}

function nextversion {
  argn 0

  local ext=`getextension $SOURCENAME`
  cp $SOURCENAME $WKDIR/versions/$VERSION.$ext
  ((VERSION++))

  updateversion $VERSION
}

function autonextversion {
  argn 0

  if b_autocompile && b_autotesting; then
    nextversion
    echo now on source ver. $VERSION
  fi
}
